name: Pages
on:
  push:
jobs:
  pages:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn
      - working-directory: packages/home
        run: |
          yarn run build
      - working-directory: packages/home
        run: |
          yarn run export
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/home/out
          cname: wagumi.xyz
